#!/usr/bin/python

# Stefan Erhardt, 2013
# This script reads the main style file, includes all imports and writes them to one file. This makes it easier to give this single file to others.
# Feel free to change, distribute, sell,...
# 

import time
import datetime

date=datetime.datetime.now().strftime("%Y-%m-%d")

filein = open("circuitikz.sty", "r")
fileout = open("../../../../circuitikz_%s.sty" %date, "w")

def readin(filename):
	filein2 = open(filename, "r")
	for line2 in filein2:
		if line2.find("\input ") != -1:
			readin(line2.strip("\input").strip())
		else:
			if line2.find("\endinput") == -1:
				fileout.write(line2)
			else:
				break				
	filein2.close()


fileout.write("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n%%%\n%%% AUTOGENERATED FILE - DO NOT EDIT THIS ONE! \n%%%\n%%% ")
fileout.write(date)
fileout.write(", Stefan Erhardt\n%%%\n%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n\n\n\n\n\n\n\n\n")

for line in filein:
	if line.find("\input ") != -1:
		readin(line.strip("\input ").strip())
	else:
		fileout.write(line)
	

#fileout.write(x)

fileout.close()
filein.close()

